version: '3'

services:
  postgres:
    image: postgres:latest
    container_name: postgres_example
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=example
      - POSTGRES_USER=example

volumes:
  postgres-data:
