#[derive(Debug)]
pub enum Type {
    Simple,
    Enum(Vec<String>),
    Pseudo,
    Array(PrimitiveType),
    Range(PrimitiveType),
    Multirange(PrimitiveType),
    Domain(PrimitiveType),
    Composite(Vec<CompositeField>),
}

#[derive(Debug)]
pub struct CompositeField {
    name: String,
    r#type: Type,
}

#[derive(Debug)]
pub enum PrimitiveType {
    Bigint,
    Bigserial,
    Bit,
    BitVarying,
    Boolean,
    Box,
    Bytea,
    Character(usize),
    CharacterVarying(usize),
    Cidr,
    Circle,
    Date,
    DoublePrecision,
    Inet,
    Integer,
    Interval,
    Json,
    Jsonb,
    Line,
    LSeg,
    Macaddr,
    Macaddr8,
    Money,
    Numeric(usize, usize),
    Path,
    PgLen,
    PgSnapshot,
    Point,
    Polygon,
    Real,
    Smallint,
    Smallserial,
    Serial,
    Text,
    Time,
    TimeWithTimezone,
    Timestamp,
    TimestampWithTimezone,
    TsQuery,
    TsVector,
    TxIdSnapshot,
    Uuid,
    Xml,
}
